albumsystem/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :albums do
    resources :songs
  end
  root 'welcome#index'
end

albumsystem/app/models/album.rb
class Album < ApplicationRecord
    has_many :songs, dependent: :destroy

    validates :title, presence: true
    validates :artist, presence: true
end

albumsystem/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album

  validates :title, presence: true
  validates :duration, presence: true
end

albumsystem/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    
    def index
        @albums = Album.all
        albumbscount = @albums.select('title').count
        if(albumbscount == 0)
            render 'noalbums'
        end
    end

    def show
        @album = Album.find(params[:id])
    end

    def new
        @album = Album.new
    end

    def edit
        @album = Album.find(params[:id])
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to @album
        else
            render 'new'   
        end 
    end

    def update
        @album = Album.find(params[:id])
       
        if @album.update(album_params)
          redirect_to @album
        else
          render 'edit'
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to albums_path
    end

    def noalbums

    end

    private
    def album_params
        params.require(:album).permit(:title, :artist)
    end

end

albumsystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

albumsystem/app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def new
        @album = Album.find(params[:album_id])
    end

    def edit
        @song = Song.find(params[:id])
    end

    def create
        @album = Album.find(params[:album_id])
        @song = @album.songs.create(song_params)
        redirect_to album_path(@album)
      end

      def destroy
        @album = Album.find(params[:album_id])
        @song = @album.songs.find(params[:id])
        @song.destroy
        redirect_to album_path(@album)
      end

      def update
        @album = Album.find(params[:album_id])
        @song = @album.songs.find(params[:id])
        @song.update(song_params)
        redirect_to album_path(@album)
      end

      private
    def song_params
      params.require(:song).permit(:title, :duration)
    end

end

albumsystem/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

albumsystem/app/helpers/albums_helper.rb
module AlbumsHelper
end

albumsystem/app/helpers/songs_helper.rb
module SongsHelper
end

albumsystem/app/helpers/welcome_helper.rb
module WelcomeHelper
end

albumsystem/app/views/albums/edit.html.erb
<h1>Edit Album</h1>
 
<%= form_with(model: @album, local: true) do |form| %>
 
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
  <strong><%= form.label :title %></strong><br>
  <%= form.text_field :title %>
</p>

<p>
<strong><%= form.label :artist %></strong><br>
<%= form.text_field :artist %>
</p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

<%= link_to 'Add a Song', new_album_song_path(@album) %> | <%= link_to 'List All Albums', albums_path %> 

albumsystem/app/views/albums/index.html.erb
<h1>Listing Albums</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th></th>
  </tr>
 
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.artist %></td>
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
      <td><%= link_to 'Delete', album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create New Album', new_album_path %>

albumsystem/app/views/albums/new.html.erb
<%= form_with scope: :album, url: albums_path, local: true do |form| %>
    
    <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
    
    <p>
      <strong><%= form.label :title %></strong><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
    <strong><%= form.label :artist %></strong><br>
    <%= form.text_field :artist %>
  </p>
   
    <p>
      <%= form.submit 'Create Album'%>
    </p>
  <% end %> 

  <%= link_to 'List All Albums', albums_path %>

albumsystem/app/views/albums/noalbums.html.erb
<h2>There are no albums in the database. Please create some albums.</h2>

<%= link_to 'Create New Album', new_album_path %>

albumsystem/app/views/albums/show.html.erb
<h2> Album Details </h2>
<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
 
<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<% if @album.songs.length !=0 %>

<h2>Songs List</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Duration</th>
  </tr>
 
  <% @album.songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>
      <td><%= song.duration %></td>
      <td><%= link_to 'Edit', edit_album_song_path(@album, song) %></td>
      <td><%= link_to 'Delete', album_song_path(@album, song),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<% end %>
<br>
<%= link_to 'Edit Album', edit_album_path(@album) %> | <%= link_to 'Add a Song', new_album_song_path(@album) %> | <%= link_to 'Create New Album', new_album_path %> | <%= link_to 'List All Albums', albums_path %> 

albumsystem/app/views/songs/edit.html.erb
<h1>Edit Song</h1>
 
<%= form_with(model: @song, url: album_song_path, local: true) do |form| %>
 
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@song.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
  <strong><%= form.label :title %></strong><br>
  <%= form.text_field :title %>
</p>

<p>
<strong><%= form.label :duration %></strong><br>
<%= form.text_field :duration %>
</p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

<%= link_to 'List All Albums', albums_path %> | <%= link_to 'Add a Song', new_album_song_path %>

albumsystem/app/views/songs/new.html.erb
<h2>Add a Song:</h2>

<%= form_with(model: [ @album, @album.songs.build ], local: true) do |form| %>
  <p>
    <strong><%= form.label :title %></strong><br>
    <%= form.text_field :title %>
  </p>
  <p>
  <strong><%= form.label :duration %></strong><br>
  <%= form.text_field :duration %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

albumsystem/app/views/welcome/index.html.erb
<h2>Album System</h2>
<br>
<%= link_to 'Create New Album', new_album_path %> | <%= link_to 'List All Albums', albums_path %>