paragraphcounter-via-JavaScript/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :counters

  root 'counters#new'

end

paragraphcounter-via-JavaScript/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

paragraphcounter-via-JavaScript/app/models/counter.rb
class Counter < ApplicationRecord
end

paragraphcounter-via-JavaScript/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

paragraphcounter-via-JavaScript/app/controllers/counters_controller.rb
class CountersController < ApplicationController
    
    def new
    end

    def show
        @counter = Counter.find(params[:id])
    end

    def create 
        @counter = Counter.new(counter_params)
        @counter.paragraph = params[:counter][:paragraph]
        p = @counter.paragraph
        # render json: {"message": paragraph}.to_json
        wordCount = p.split(' ').length
        
        # render json: {"message": paragraph}.to_json
        # @charCount = paragraph.gsub!(/\s+/, "").length
        @counter.charcount = p.gsub(/\s+/, "").length
        @counter.wordcount = wordCount
        if @counter.save
        redirect_to @counter, notice: 'Counter was successfully created'  
        else 
        render json: {"message": "not saved"}.to_json
        end
    end

 private
    def counter_params
        params.require(:counter).permit(:paragraph, :charcount, :wordcount)
    end

end

paragraphcounter-via-JavaScript/app/helpers/application_helper.rb
module ApplicationHelper
end

paragraphcounter-via-JavaScript/app/helpers/counters_helper.rb
module CountersHelper
end

paragraphcounter-via-JavaScript/app/views/counters/new.html.erb
<form>
  <strong>Type your paragraph:</strong><br>
  <textarea name="paragraph" id="paragraph"></textarea>
  <input type="button" onClick="counter()" value="Submit" >
</form> 

<span id="wordcount"></span>
<span id="charcount"></span>

paragraphcounter-via-JavaScript/app/views/counters/show.html.erb
<p>
<strong>Your Paragraph:</strong>
<%= @counter.paragraph %>
</p>

<p>
<strong>Character Count</strong>
<%= @counter.charcount %>
</p>

<p>
<strong>Word Count</strong>
<%= @counter.wordcount %>
</p>

<%= link_to 'Back', new_counter_path %>